### ISSUE TITLE
Build as per readme instructions fails

### ISSUE THREAD

**Issue by mihbor** [berndruecker/flowing-retail-old#1]
Readme instructions suggest building is as simple as running mvn install, however, this is not the case.
Multiple modules fail to build due to artifacts not being present in mvn central.
Some of these (order and payment modules) can be fixed simply by adding the camunda public repo to the respective poms. 
bpmn-monitor is harder to fix, so I gave up trying to do it myself. 
It seems to have dependencies on artifacts not present in the camunda repo. I am guessing they come from https://github.com/camunda/camunda-consulting but don't have time right now to try to get them working and submit a PR.

I kindly suggest you try the building according to your readme instructions against an empty local maven repo and default ~/.m2/settings.xml to see the errors it produces.
I'll give this another go if and when I have more time, the project looks super cool and I'd like to be able to demo it to "the business" :-)

**Comment by berndruecker** [comment]
I can confirm this. I will add the public repo and remove the bpmn-monitor from the repo - as it requires an camunda enterprise edition to properly show history.

**Comment by berndruecker** [comment]
@mihbor Would be great if you can give it another try. I am actually on vacation and just fixed it in between ;-)

**Comment by berndruecker** [comment]
Moved the monitor to own repo: https://github.com/berndruecker/flowing-retail-camunda-bpmn-monitor

**Comment by mihbor** [comment]
Awesome, thanks!
